name: NuGet Akc.Duende.IdentityServer.Management.Api

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/Management/Api/**'

env:
  BuildNumber: "${{ contains(github.ref, '/release/') && '' || format('preview.{0}', github.run_id) }}"

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Add coverlet package
        working-directory: ./src/Management/Api/Akc.Duende.IdentityServer.Management.Api.Tests/
        run: dotnet add package coverlet.collector --no-restore

      - name: Test
        working-directory: ./src/Management/Api/Akc.Duende.IdentityServer.Management.Api.Tests/
        run: |
          dotnet test --configuration Release \
            --collect:"XPlat Code Coverage" \
            --results-directory coverage \
            --logger trx

      - name: Copy Coverage To Predictable Location
        working-directory: ./src/Management/Api/Akc.Duende.IdentityServer.Management.Api.Tests/
        run: cp coverage/**/coverage.cobertura.xml coverage/coverage.cobertura.xml

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.0.5
        with:
          filename: ./src/Management/Api/Akc.Duende.IdentityServer.Management.Api.Tests/coverage/coverage.cobertura.xml
          badge: true
          format: 'markdown'
          output: 'both'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md

      - name: Build
        working-directory: ./src/Management/Api/Akc.Duende.IdentityServer.Management.Api/
        run: |
          dotnet build --configuration Release -p:BuildNumber=${{ env.BuildNumber }} -p:IsLocalBuild=False

      - name: Pack
        working-directory: ./src/Management/Api/Akc.Duende.IdentityServer.Management.Api/
        run: |
          dotnet pack --no-build --configuration Release -p:BuildNumber=${{ env.BuildNumber }} -p:IsLocalBuild=False

      - name: Push
        working-directory: ./src/Management/Api/Akc.Duende.IdentityServer.Management.Api/
        run: |
          dotnet nuget push \
            --api-key ${{ github.token }} \
            --source https://nuget.pkg.github.com/arkiaconsulting/index.json \
            --skip-duplicate \
            ./.nupkg/*
        