name: NuGet Duende.IdentityServer.Akc.Management.Api

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/Management/Duende.IdentityServer.Akc.Management.Api/**'

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
          configFilePath: ./.github/gitversion.yml  

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Install dependencies
        run: dotnet restore
        working-directory: ./src/Management/Duende.IdentityServer.Akc.Management.Api/

      - name: Build
        working-directory: ./src/Management/Duende.IdentityServer.Akc.Management.Api/
        run: |
          dotnet build --configuration Release --no-restore \
            /p:Version=${{ steps.gitversion.outputs.AssemblySemVer }} \
            /p:AssemblyVersion=${{ steps.gitversion.outputs.AssemblySemVer }} \
            /p:InformationalVersion=${{ steps.gitversion.outputs.InformationalVersion }}

      - name: Test
        working-directory: ./src/Management/Duende.IdentityServer.Akc.Management.Api/
        run: |
          dotnet test --configuration Release --no-build --no-restore --verbosity normal \
            /p:Version=${{ steps.gitversion.outputs.AssemblySemVer }}

      - name: Push
        working-directory: ./src/Management/Duende.IdentityServer.Akc.Management.Api/
        run: |
          dotnet pack --no-restore --output ./.nupkg --configuration Release \
            /p:PackageVersion=${{ steps.gitversion.outputs.NuGetVersion }}
          dotnet nuget push \
            --api-key ${{ github.token }} \
            --source https://nuget.pkg.github.com/arkiaconsulting/index.json \
            --skip-duplicate \
            ./.nupkg/*
        