name: Sample App

on:
  push:
    branches: [ main ]
    paths:
      - 'src/Samples/InMemory/**'

env:
  AZURE_WEBAPP_NAME: akc-duende
  AZURE_WEBAPP_PACKAGE_PATH: './src/Samples/InMemory/'
  DOTNET_VERSION: '6.0.x'

jobs:
  deploy-in-memory-sample-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build and publish
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o './app' 

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/app'

      - name: logout
        run: |
          az logout

